### ISSUE TITLE
Request to use javafx-calendar library

### ISSUE THREAD

**Issue by lyskevin** [nus-cs2103-AY1920S1/forum#127]
## Library

[javafx-calendar](https://github.com/SirGoose3432/javafx-calendar)

## Purpose

Implement calendar view in TP application

**Comment by damithc** [comment]
Does not seem to be a well-established library. Are you sure this is the best option? Anyway, you may use at your own risk.

**Comment by j-lum** [comment]
- Your proposed library uses Java to generate the controls which will result in two different paradigms in the same codebase (since AB3 choose to go with FXML). 
- The project seems to be abandonware. 
- Other teams have requested to use other packages which provide similar functionality. 
- More feature complete alternatives exist.

**Comment by lyskevin** [comment]
Ok thanks for the advice! I will look into other libraries first then.
