### ISSUE TITLE
UIPartTest fail

### ISSUE THREAD

**Issue by Ellieyee** [nus-cs2103-AY1920S1/forum#133]
## Environment

main forked from addressbook3, runs on java11

## Issue

After adding new UI increments my tests for UiPartTest seem to fail. Specifically the 
constructor_missingFileUrl_throwsAssertionError() and 
constructor_invalidFileUrl_throwsAssertionError(). 
However, I have not modified the existing UIPart neither have I created any new UIPart within this iteration. (previous iterations have all passed).
Moreover, gradlew test shows Build Successful as well as my build report), whereas travis shows a build failed during the PR.
https://travis-ci.org/AY1920S1-CS2103-T14-2/main

## Code/Log Trace

My changes can be viewed here: https://github.com/AY1920S1-CS2103-T14-2/main/pull/61/files

**Comment by shaoyi1997** [comment]
Hmmm, based on the Travis job log it seems like the build failure is not due to `constructor_missingFileUrl_throwsAssertionError()` and `constructor_invalidFileUrl_throwsAssertionError()` tests failures.

Rather, it's due to an `AssertionFailedError` in your `TutorialTest`, as seen below.

![image](https://user-images.githubusercontent.com/44439414/66765781-3670f180-eedf-11e9-80eb-4b6cc381b5a2.png)

**Comment by damithc** [comment]
@Ellieyee is the issue resolved?

**Comment by Ellieyee** [comment]
yes! Thanks @shaoyi1997 :)
