### ISSUE TITLE
Association label vs association role

### ISSUE THREAD

**Issue by CoderStellaJ** [nus-cs2103-AY1920S1/forum#135]
Can anyone help to point out why this diagram is false? And what's the difference between association role and association label? Thanks!

Quiz question:
Which diagrams are acceptable representations of the **highlighted association role**?
![Capture](https://user-images.githubusercontent.com/40347063/66929240-461a4280-f065-11e9-846e-2da5da680960.PNG)

**Comment by ambervoong** [comment]
Association roles are used to indicate the **role played by the classes** in the association. For example, in an association between classes A and B, class A could play the role of the husband and class B plays the role of the wife. 

Association labels are the ones shown in the diagram you linked. They **describe the meaning of the association**.  An easy way to distinguish between them is the black arrow present in association labels. Also, it often describes a relationship whereas association roles tend to be nouns like 'friend' or 'helper'!

This diagram is false because an association label is shown in the diagram, not an association role. I can't remember exactly but I think the question was asking this was a valid association role! Otherwise, it is a perfectly valid association label.

**Comment by CoderStellaJ** [comment]
Thanks for your contribution to this question. 
Because the quiz question asks whether the diagram shows the correct association role but the diagram shows association label. The diagram fails to show the role.
