### ISSUE TITLE
Unable to open JAR file

### ISSUE THREAD

**Issue by jaesimin** [nus-cs2103-AY1920S1/forum#138]
Please read up on how to write a [good question](https://stackoverflow.com/help/how-to-ask)

## Environment

Describe your development environment

- IntelliJ version: 2019.2.2
- Java version: 11.0.2
- Operating system version: Windows 10
- _other packages' versions_

## Issue

Unable to double-click / run the command `java -jar duke-0.2.jar` for the JAR file that I had created using `gradlew shadowJar` . I am only able to right-click the JAR file and run it in IntelliJ. 

I had added and removed the dependencies according to #72.

There's no error in all the steps. The JAR file just doesn't work. Why?

## Code/Log Trace

Executing `gradlew run' works:

![image](https://user-images.githubusercontent.com/54024708/67156031-1cef0000-f34c-11e9-86c3-96b4184dff8b.png)

Running `java -jar duke-0.2.jar` command:

![image](https://user-images.githubusercontent.com/54024708/67156005-ced9fc80-f34b-11e9-80fe-c921f305ea6f.png)

Right-clicking JAR file in Intellij works:

![image](https://user-images.githubusercontent.com/54024708/67156013-ea450780-f34b-11e9-9422-5c9b8ceadb68.png)

![image](https://user-images.githubusercontent.com/54024708/67156025-f92bba00-f34b-11e9-96c6-a65c26c051fb.png)

**Comment by dawo5010** [comment]
Remove the following lines from your build.gradle

`id 'org.openjfx.javafxplugin' version '0.0.7' //javafx` (line 6)
and
`javafx {
    version = "11.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}` (line 23-27)
they are no longer required as the JavaFX dependencies will be specified by lines 43 - 60 instead (you can also optionally choose to remove line 55 - 60 as they are unnecessary).

Your jar file generated by shadowJar should then be able to run on any system.

However, I noticed another bug during testing - your program won't launch if the file data/duke.txt is not present. You might want to look into ways to create the file automatically instead of throwing an exception and closing - see https://github.com/nus-cs2103-AY1920S1/forum/issues/27

Hope that helps! :)

**Comment by jaesimin** [comment]
Thank you! It works already :)
