### ISSUE TITLE
Question on how to revert commits

### ISSUE THREAD

**Issue by gachia** [nus-cs2103-AY1920S1/forum#21]
Hello,

For Level 7, I've unintentionally committed the merge of Level 7 with fast forward (by default) and I'm unsure of how to revert this commit.

After committing Level 7, I have also committed Level 8 (successfully without fast forward; can see "merge branch" commit) and that was when I realised what it meant by merging without fast forward.

How do I safety revert the commits for me to be able to merge branch Level 7 into master again without fast forward?

**Comment by shawnkoh** [comment]
Git log
Find the commit hash before you merged level 7

git reset —hard hash

Merge them again

git push -f

**Comment by TheRealRavager** [comment]
Thanks Shawn, I believe your solution should quickly solve OP's issue. Lets take a moment to appreciate the difference between a revert and reset. [This](https://stackoverflow.com/questions/8358035/whats-the-difference-between-git-revert-checkout-and-reset) StackOverflow post should explain things pretty clearly.

TL:DR, a revert introduces another commit that basically undoes the reverted commit. A reset however, undoes changes by changing the commit history. 

An analogy would be as such: 
Imagine you were writing an essay and for every revision you would have a new copy (i.e. essay1.docx, essay2.docx, essay3.docx, essay4.docx). You mistakenly deleted your entire intro paragraph in essay3.docx and need to fix it. A revert would be to undo the deletion and save it as essay5.docx while a reset would be to delete everything from essay3.docx onwards and start from essay2.docx.

If you have the time to spare, I highly recommend [this](https://learngitbranching.js.org/) git tutorial. It gives really simple and elegant real-time visualisations of git branches as you perform commands, so you get a rough idea of whats happening to the commit history instead of it feeling like you're just playing with magical commands.

**Comment by shawnkoh** [comment]
Thanks for taking the time to explain git revert in detail Iskandar!

I'd like to add on a cautionary note about tags since we are on the note of reverting/reseting commits.

If you have pushed your tags to your remote repo with git push --tags, reverting or deleting your commits will not remove your tags on the remote repo.

So how do we resolve this?

You may be tempted to use
```git tag --delete``` but this only deletes them locally.

Instead, you have to use
```git push origin :tagname```

Please refer to this stackoverflow post for a more in depth discussion about removing tags on remote repos. https://stackoverflow.com/questions/5480258/how-to-delete-a-remote-tag

**Comment by gachia** [comment]
Thank you Shawn and Iskandar for the help and info! I did Shawn's quick solution and managed to get the Merge commit up. Nonetheless, I appreciate and have noted the information both of you have shared😊.
