### ISSUE TITLE
How do I get Gradle to use JDK 11 to build

### ISSUE THREAD

**Issue by gachia** [nus-cs2103-AY1920S1/forum#28]
Hello,

I tried to implement Gradle into my project and wanted to test if Gradle is working correctly as per tutorial instructions. However, the build failed and it mentions that it is using my old jdk 8 folder (the source of the error) instead of my current jdk 11, which the project is running on. How do I point Gradle to use the jdk 11 folder to build?

**Comment by dawo5010** [comment]
I presume you're on Windows 10.
Try editing your System Environment Variables:

1. Search Environment Variables in your start menu search bar:
![Untitled](https://user-images.githubusercontent.com/4518827/63953016-18783a80-cab3-11e9-9cb9-08d1b37f8557.png)

2. Click Environment Variables:
![Annotation 2019-08-29 231404](https://user-images.githubusercontent.com/4518827/63953062-30e85500-cab3-11e9-93ef-4a17aea1f461.jpg)

3. Under system variables, look for a JAVA_HOME and double click it and modify the variable value to the path of your JDK 11 (without the /bin folder).
If it doesn't exist, create one (but I presume it should, since gradle is already working, else it would throw an error message.)
![Annotation 2019-08-29 231346](https://user-images.githubusercontent.com/4518827/63953040-25952980-cab3-11e9-8853-7607680cffce.jpg)

The steps would differ if you use Mac OS (and I am not too sure, since it worked out of box for me), but you can try referring to [this Medium article](https://medium.com/zendesk-engineering/setting-java-home-on-mac-os-acd44e3a6027) for that.

**Comment by gachia** [comment]
Thanks for the help! I managed to resolve it. Initially it didn't work even though I've set the system variable, so I had to restart my com and it worked afterwards.

**Comment by j-lum** [comment]
Note that while this is one solution, there are other solutions which may be equally (if not more appropriate/viable). 

https://docs.gradle.org/current/userguide/build_environment.html

**Comment by damithc** [comment]
Thanks for the help @dawo5010 @j-lum
