### ISSUE TITLE
📣 Anybody fixed failing tests after AB3's  Add-Remark tutorial?

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY1920S1/forum#88]
Some of you reported that some tests fail at the end of the AB3's [Add-Remark tutorial](https://nus-cs2103-ay1920s1.github.io/addressbook-level3/tutorials/AddRemark). If anyone managed to fix the failing tests, please share your solution here for the benefit of others.

**Comment by ChrisKheng** [comment]
I faced similar issues as well and what I did is I first determine which test fails first and also why it fails (from the console which shows the assertions error). The most common problem I faced is the actual `Command` or `CommandResult` generated is **not equal** to the expected one. It's usually due to differences in some values, for example, the content of the `remark` in the `CommandResult`, which is usually because of putting different values for the field in where the expected result is generated and where the actual command is generated. (sometimes the result is generated from the data file)

I put a breakpoint at the relevant line before the assertion in the test method (which fails) and run the debugger and track the value of `Command` and/or `CommandResult` step by step, stepping into the relevant methods as necessary. I focus especially on the value(inner content) of `Command` or `CommandResult`, e.g. `name` and `address`. When I found out the point **where the difference in value occurred**, I will do some backtrack to find **where** the actual `Command` and/or `CommandResult` is generated to see what causes the differences in value.

Hope this helps!

**Comment by Parcly-Taxel** [comment]
The strange thing is, even after complaining about the test failures in the lecture, I managed to fix them with the IDE debugger (see #87 and my branch's commits linked from there, e.g. [this](https://github.com/Parcly-Taxel/main/commit/8475c2f822eecf570a475af7250f18d313acd292)). Setting breakpoints in the code helped to show which test objects had not been updated to use the new remark syntax.

**Comment by KendrickAng** [comment]
The fixes mainly involve integrating the Remark class with the rest of addressbook. I've also put my changes in a [commit](https://github.com/KendrickAng/main/commit/9b7159bc66317fb7a83e9fbe76bba82b15c8c0a5). 

Here's my (very incomplete) notes trying to figure out what went wrong:

1. execute_storageThrowsIoException_throwsCommandException
- AddCommandParser should be able to parse remarks from the argMultiMap. If this was the first test case failure you looked at, AddCommandParser#parse still returns a new Remark("") as stated in the tutorial, which is incorrect.

2. parse_optionalFieldsMissing_success()
- AddCommandParser needs to support remark parsing (like the above). 

3. parse_allFieldsPresent_success()
- Update PersonBuilder and AddCommandParserTest#asserParseSuccess's _userInput_ fields.

4. toModelType_typicalPersonsFile_success()
- JsonAdaptedPerson.java detects that your remarks are null (because we haven't added them).
- update typicalPersonsAddressBook.json to include the "remark" json object field.
- There's also no remark in TypicalPersons.java (which should match typicalPersonAddressBook.java), so this cases the default remark in PersonBuilder to be used instead, giving us incorrect output.

5. toModelType_duplicatePersons...
- duplicatePersonAddressBook.json is missing a remark field. Add **the same** remark for both json objects in the file.

-> Fixing some of these errors caused others to spring up:
6. execute_allFieldsSpecifiedUnfiltered
- The EditCommand needs to allow editing remarks too.
- Update: EditCommand.java, EditPersonDescriptor.java, EditPersonDescriptorBuilder.java
6.1 This causes the parseCommand_edit... test case to fail.
- update EditCommandTest#getEditPersonDescriptorDetails to include remarks.

Hope this helps!

**Comment by hoholyin** [comment]
We can make use of the debugger in Intellij to 'Step in' the failing tests. 
After stepping through a few levels, we will realise that most of the failing tests are due to the fact in the file `CommandTestUtil.java`, we are missing:
1) `public static final String VALID_REMARK_AMY = "valid remark amy"`
2) `public static final String VALID_REMARK_BOB = "valid remark bob"` 
(These are as per the other fields required in building a `Person` object).

Adding these two final Strings and using them in the tests will allow most tests to pass as expected.

We also need to take note that these stub remarks will need to be consistent with the ones in the `TypicalPersonsAddressBook.json` for the test to pass since the test will compare between the constructed person and the person stored in the .json file.

**Comment by ambervoong** [comment]
Along with the debugger, using _Go To -> Implementation_ is very useful to quickly view a method's code. In addition to the above, here are fixes for two other failing test cases. Hope it will be of use to someone. 

1. `parseCommand_remark()`
- In `AddressBookParserTest.java`, update `assertEquals(new RemarkCommand(INDEX_FIRST_PERSON, remark), command);` to make `remark` a Remark object instead of a String.

2. `parseCommand_add()`
- `AddCommandParser.java` only returns new Remark(""). As mentioned above, update the code and add a new method to parse remarks in `ParserUtil.java`.
- `PersonUtil.getAddCommand(person)` calls `getPersonDetails(Person person)` which extracts the Person's details. Update it to support remarks by adding `sb.append(PREFIX_REMARK + person.getRemark().value + “ “);`

**Comment by Parcly-Taxel** [comment]
When are you going to close this one?

**Comment by damithc** [comment]
> When are you going to close this one?

Let's leave it open for a few more days. Some are still doing the tutorials. I'll close it later.
